[package]
name = "gpgmime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sequoia-openpgp = "1.10.0"
mail-builder = "0.2.2"
base64 = "0.13.0"
